### ISSUE TITLE
Organize Xcode project

### ISSUE THREAD

**Issue by brennanMKE** [GiveNow/givenow-ios#1]
As we discussed at the first meeting the Xcode project will use CocoaPods to manage dependencies and will not use an integrated workspace. The following command is used to install the pods in this way.

```
pod install --no-integrate
```

We will use minimal dependencies at the start and break up the project into different user flows so that work in storyboards can be done with separate storyboard files.
- [x] Remove workspace
- [x] Update Podfile
- [x] Install dependencies with `pod` command
- [x] Manually add framework references to project
- [ ] Set up `copy frameworks` script to strip architectures for iTunes Connect submission
- [ ] Create a Staging build target to support the development backend
- [x] Remove `Pods` folder from source control (it was already added before)
- [ ] Move project folders to root folder

**Comment by brennanMKE** [comment]
This task is complete for now and the final steps will be completed once the dependencies are included in the project. @casademora is working on that next.

**Comment by mkulumadzi** [comment]
We may create new issues for the unfinished tasks
