### ISSUE TITLE
Create onboarding flow (with blank screen for registration/login)

### ISSUE THREAD

**Issue by brennanMKE** [GiveNow/givenow-ios#4]
Handle just the first launch flow for onboarding users. The registration/login flow will be handled by a separate view controller which can be dropped in a view as a child view controller to handle that interaction.
- [x] Create paged sequence which is a tutorial or the app (copy the Android app)
- [x] Allow user to swipe forward and back

This flow could be built simply with a collection view. Each cell will have an image and a label. A page control over the collection view will show the current position. The final 2 screens are for the registration/login process for the user. If these scenes are built as separate view controllers they could be developed a bit more easily  and repurposed outside of the onboarding flow later if it changes.

**Comment by aphexcx** [comment]
Complete :+1:
