### ISSUE TITLE
Create registration/login flow which will be dropped into first launch flow

### ISSUE THREAD

**Issue by brennanMKE** [GiveNow/givenow-ios#5]
See: https://github.com/GiveNow/givenow-ios/issues/4
- [x] Take in user's phone number and validate the format
- [x] Send number to backend to generate 4 digit access code
- [x] Take in access code to verify the user login
- [x]  Procede to the main screen of the app

**Comment by brennanMKE** [comment]
@mrbombastic You can see how the volunteer flow is handling the phone number and entry code to let the user log in.

**Comment by aphexcx** [comment]
On Android, this is implemented with a single shared fragment (`PhoneNumberVerificationFragment`). This fragment is displayed in three places: 
1) embedded in the onboarding flow
2) As a standalone modal when completing the request pickup flow and applying to volunteer.

If iOS has the same facility for sharing ui/controllers, I'd recommend doing the same thing to maximize code reuse.

**Comment by mrbombastic** [comment]
Sure I will take a look.

**Comment by mkulumadzi** [comment]
I'm going to take this on now - seems like a logical next thing to work on having just reworked the main navigation.

**Comment by mkulumadzi** [comment]
Done! See #50
