### ISSUE TITLE
Apply-to-Volunteer flow refinements

### ISSUE THREAD

**Issue by aphexcx** [GiveNow/givenow-ios#54]
Minor polish needed to get applying to volunteer working to spec:
## On first display of the volunteer screen

Check the current user's eligibility to see the volunteer tabs (i.e., the dashboard & open pickup requests tabs).
- Search the volunteer table for the current user. If found, proceed to **Approval Check**. If not found, then the user never applied to be a volunteer. Show the green "I Want to Volunteer" button. [Android implementation](https://github.com/givenow/givenow-android/blob/8fb6bf72a079a5e450a597d6d6779370ea5a8eaa/app/src/main/java/io/givenow/app/fragments/main/VolunteerFragment.java#L80-L91)
## On "Apply to Volunteer" Click

If user `.isRegistered()`, proceed to **Volunteer Application**. If not registered (anoynmous), show addPhoneNumber modal. 
- When addPhoneNumber modal completes successfully, _log the user in_ and proceed to **Volunteer Application**. [Android implementation](https://github.com/givenow/givenow-android/blob/8fb6bf72a079a5e450a597d6d6779370ea5a8eaa/app/src/main/java/io/givenow/app/fragments/main/VolunteerFragment.java#L93-L104)
## Volunteer Application

Search the volunteer table for the current user. If found, proceed to **APPROVAL CHECK**. If not found, then add the user to the volunteer table. [Android implementation](https://github.com/givenow/givenow-android/blob/8fb6bf72a079a5e450a597d6d6779370ea5a8eaa/app/src/main/java/io/givenow/app/fragments/main/VolunteerFragment.java#L115-L120)
## Approval Check

[Android implementation](https://github.com/givenow/givenow-android/blob/8fb6bf72a079a5e450a597d6d6779370ea5a8eaa/app/src/main/java/io/givenow/app/fragments/main/VolunteerFragment.java#L125-L135)
If the volunteer`.isApproved()`, then show the volunteer tabs. If not approved, show [**awaiting approval** state](https://github.com/givenow/givenow-android/blob/8fb6bf72a079a5e450a597d6d6779370ea5a8eaa/app/src/main/java/io/givenow/app/fragments/main/VolunteerFragment.java#L137-L143).

**Comment by mkulumadzi** [comment]
I think this is pretty close already. This is how it works right now:

1) If the user is logged in but not a volunteer, they see the "I want to volunteer" application
2) If the user is logged in and is a pending volunteer, they see the "you applied" screen
3) If the user is not logged in, they see the "I want to volunteer" application. If they click the button, they are asked to log in, and then the application is created

Are you saying that, in case 3, you would like to see them to see the login workflow before they see the "I want to volunteer"? application?

**Comment by aphexcx** [comment]
:+1:
