### ISSUE TITLE
Integrate Crashlytics Crash Reporting

### ISSUE THREAD

**Issue by aphexcx** [GiveNow/givenow-ios#59]
Crashlytics is part of the Fabric SDK (super easy to integrate). https://get.fabric.io/ios?locale=en-us

PM me on Slack for the login.

**Comment by brennanMKE** [comment]
We can just use Apple's crash reporting which is now integrated with Xcode and requires no effort. We also do not want to use anything from Fabric. It's not good software.

**Comment by aphexcx** [comment]
+1 for using Apple's crash reporting in addition to Crashlytics. Just wondering, what's your beef with it? Interested to hear - I've been using Crashlytics on Android since before Twitter bought them and integrated it into Fabric, and it's been nothing but win. To be consistent, I want it running on the iOS app too.
