### ISSUE TITLE
Ask donor if donation is ready for pickup

### ISSUE THREAD

**Issue by mkulumadzi** [GiveNow/givenow-ios#65]
As a volunteer, I want the donor to tell me if their donation is ready to be picked up so that I know whether I can go and collect it.
- [x] Display modal dialogue on top of 'new donation' view if a pickup request has a pending volunteer
- [x] If user clicks 'no', clear the pending volunteer
- [x] If user clicks 'yes', make the pending volunteer a confirmed volunteer, and update the header of this view to say something like "The volunteer is en route"

**Comment by mkulumadzi** [comment]
![screen shot 2016-01-16 at 2 53 32 pm](https://cloud.githubusercontent.com/assets/5233147/12374937/7b810f94-bc61-11e5-9c94-65a8e271c01b.png)

**Comment by aphexcx** [comment]
[Dialog implementaton in Android](https://github.com/givenow/givenow-android/blob/278bb58482c88227b7954e137f41da871e540474/app/src/main/java/io/givenow/app/activities/MainActivity.java#L228-L255)

**Comment by aphexcx** [comment]
On Yes click, you'll call the "confirmVolunteer" cloud function. I implemented these cloud calls on the pickupRequest object, you might want to do that too. See here:
https://github.com/givenow/givenow-android/blob/6109af1d61bf73aa4e7bd4ee237e28e42f48ad4a/app/src/main/java/io/givenow/app/models/PickupRequest.java#L261-L280
